/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project2.com.entitys;

import Project2.DangKy;
import Project2.DangNhapNV;
import Project2.Main;
import Project2.NvAndNvacc;
import Project2.com.dao.ConnectionDB;
import Project2.com.dao.NhanVienDB;
import Project2.com.dao.Utils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Minh PC
 */
//?serverTimezone=UTC
public class NhanVien extends javax.swing.JFrame {

    private int maEmployee;
    private String employeeName, address, Email, phonenumber, tenTaiKhoan, matKhau, loai;
//   String a =""+money  ;
    private String birthDate;

    public String getTenTaiKhoan() {
        return tenTaiKhoan;
    }

    public void setTenTaiKhoan(String tenTaiKhoan) {
        this.tenTaiKhoan = tenTaiKhoan;
    }

    public String getMatKhau() {
        return matKhau;
    }

    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }

//    public int getMaRegister() {
//        return maRegister;
//    }
//
//    public void setMaRegister(int maRegister) {
//        this.maRegister = maRegister;
//    }
    public int getMaEmployee() {
        return maEmployee;
    }

    public void setMaEmployee(int maEmployee) {
        this.maEmployee = maEmployee;
    }

    public String getEmployeeName() {
        return employeeName;
    }

    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String email) {
        Email = email;
    }

    public String getPhonenumber() {
        return phonenumber;
    }

    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    public String getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    public String getLoai() {
        return loai;
    }

    public void setLoai(String loai) {
        this.loai = loai;
    }

    /**
     * Creates new form NhanVien
     */
//    class CollectionJava {
//
//        public Connection ketNoi() throws ClassNotFoundException, SQLException {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_quanlysach?serverTimezone=UTC", "root", "");
//            //db_demo là tên của database, root là username và password là rỗng
//            return con;
//
//        }
//    }
    DefaultTableModel model;
    private ArrayList<NhanVien> list;

    public NhanVien() {
        initComponents();
        this.setLocationRelativeTo(null);
        list = new ArrayList<>();
        model = (DefaultTableModel) Table.getModel();
        ShowTableInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        UpdateButton = new javax.swing.JButton();
        ngaySinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        diaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        DeleteButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ClearButton = new javax.swing.JButton();
        tenNhanVien = new javax.swing.JTextField();
        SDT = new javax.swing.JTextField();
        InsertButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        register_uname = new javax.swing.JTextField();
        register_password = new javax.swing.JPasswordField();
        register_retype_password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        adminRadioB = new javax.swing.JRadioButton();
        nvRadioB = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jPanel2.setBackground(new java.awt.Color(44, 63, 80));

        UpdateButton.setBackground(new java.awt.Color(255, 255, 255));
        UpdateButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/update-icon.jpg"))); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        ngaySinh.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ngaySinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ngaySinhFocusLost(evt);
            }
        });
        ngaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaySinhActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên Nhân Viên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ngày Sinh:");

        email.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/backpage-icon.png"))); // NOI18N
        jButton1.setText("BackPage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email:");

        diaChi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        diaChi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                diaChiFocusLost(evt);
            }
        });
        diaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaChiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Địa Chỉ:");

        Table.setBackground(new java.awt.Color(255, 255, 255));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Địa Chỉ", "Ngày Sinh", "Email", "SDT", "Tên Tài Khoản", "Loại"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        DeleteButton.setBackground(new java.awt.Color(255, 255, 255));
        DeleteButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/delete-icon.jpg"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số Điện Thoại:");

        ClearButton.setBackground(new java.awt.Color(153, 153, 255));
        ClearButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(255, 255, 255));
        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/clear-icon.png"))); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        tenNhanVien.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tenNhanVien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tenNhanVienFocusLost(evt);
            }
        });
        tenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenNhanVienActionPerformed(evt);
            }
        });

        SDT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SDTFocusLost(evt);
            }
        });
        SDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SDTKeyTyped(evt);
            }
        });

        InsertButton.setBackground(new java.awt.Color(255, 255, 255));
        InsertButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        InsertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/insert-icon-21.jpg"))); // NOI18N
        InsertButton.setText("Insert");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tên Tài Khoản: ");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mật Khẩu:");

        register_uname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        register_uname.setForeground(new java.awt.Color(108, 122, 137));

        register_password.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        register_retype_password.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        register_retype_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                register_retype_passwordFocusLost(evt);
            }
        });
        register_retype_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_retype_passwordActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nhập lại Mật Khẩu:");

        buttonGroup1.add(adminRadioB);
        adminRadioB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        adminRadioB.setForeground(new java.awt.Color(255, 255, 255));
        adminRadioB.setText("Admin:1");
        adminRadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRadioBActionPerformed(evt);
            }
        });

        buttonGroup1.add(nvRadioB);
        nvRadioB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nvRadioB.setForeground(new java.awt.Color(255, 255, 255));
        nvRadioB.setText("Nhân Viên:2");
        nvRadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvRadioBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Loại");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("copyright © by ProjectThuVien");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(adminRadioB)
                                .addGap(30, 30, 30)
                                .addComponent(nvRadioB)))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InsertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ngaySinh)
                            .addComponent(diaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tenNhanVien))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(register_retype_password, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SDT, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                    .addComponent(register_uname)
                                    .addComponent(register_password))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(register_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(register_password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(register_retype_password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminRadioB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nvRadioB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thông Tin Nhân Viên");

        jLabelClose.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelClose)
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void ShowTableInfo() {
        //xoá hết tất cả các hàng trong table
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        //hiển thị tất cả các dữ liệu từ các cột lên trên table
        Vector vector = new Vector();
        try {
            Connection con = Project2.com.dao.ConnectionDB.ketNoi();
            Statement stateMent = con.createStatement();
            ResultSet rs = stateMent.executeQuery("select * from nhanvien");
            while (rs.next()) {
                //System.out.println(rs.getInt(1)+" "+ rs.getString(2)+" "+rs.getString(3));
                vector = new Vector();
                vector.add(rs.getString(1));
                vector.add(rs.getString(2));
                vector.add(rs.getString(3));
                vector.add(rs.getString(4));
                vector.add(rs.getString(5));
                vector.add(rs.getString(6));
                vector.add(rs.getString(7));
                vector.add(rs.getString(9));
                model.addRow(vector);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
//        int IdNhanVien = Integer.parseInt(maNhanVien.getText());
        String password = register_password.getText();
//        String IdDangKy = jComboBox_maTaiKhoan.getSelectedItem().toString();
        String TenNhanVien = tenNhanVien.getText();
        String DiaChi = diaChi.getText();
        String NgaySinh = ngaySinh.getText();
        String Email = email.getText();
        String sDT = SDT.getText();

        String uname = register_uname.getText();
        String mahoa = Utils.getMd5(password);
        int row = Table.getSelectedRow();
//        TableModel model= Table.getModel();
        String IdNhanVien = (Table.getModel().getValueAt(row, 0).toString());
        String loai =  null;
        if (adminRadioB.isSelected()) {
            loai = adminRadioB.getText();
        }
        if (nvRadioB.isSelected()) {
            loai = nvRadioB.getText();
        }
        condition();
        if (condition == true) {
            NhanVienDB.updateData(Integer.parseInt(IdNhanVien), TenNhanVien, DiaChi, NgaySinh, Email, sDT, uname, mahoa,loai);
            
        } else if (condition == false) {
            JOptionPane.showMessageDialog(this, "Sửa tài khoản thất bại");
            condition = true;
            return;
        }
        ShowTableInfo();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void ngaySinhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ngaySinhFocusLost

    }//GEN-LAST:event_ngaySinhFocusLost

    private void ngaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngaySinhActionPerformed

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost

    }//GEN-LAST:event_emailFocusLost

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_emailKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NvAndNvacc nvacc = new NvAndNvacc();
        nvacc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void diaChiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diaChiFocusLost

    }//GEN-LAST:event_diaChiFocusLost

    private void diaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaChiActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
         int row = Table.getSelectedRow();
         String Ma = (Table.getModel().getValueAt(row, 0).toString());       
         NhanVienDB.deleteData(Integer.parseInt(Ma));               
        ShowTableInfo();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed

        clearField();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void SDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SDTFocusLost

    }//GEN-LAST:event_SDTFocusLost

    private void SDTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SDTKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_SDTKeyTyped
   
boolean condition = true;
    void condition() {
         
        
//ten nhan vien
        String TEN = tenNhanVien.getText();
        //
        if (TEN.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(tenNhanVien, "Bạn không được để trống tên nhân viên");
            condition = false;
        }

//dia chi
        String DIACHI = diaChi.getText();
        //
        if (DIACHI.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(diaChi, "Bạn không được để trống địa chỉ");
            condition = false;
        }

//ngay sinh       
        String NGAYSINH = ngaySinh.getText();
        // vi du :21//08//2004
        String check1 = "\\d{1,2}[//]\\d{1,2}[//]\\d{4}";
        //
        if (NGAYSINH.length() > 0) {
            if (!NGAYSINH.matches(check1)) {
                JOptionPane.showMessageDialog(ngaySinh, "Sai định dạng ngày sinh, nhập lại ngày tháng năm !, ví dụ: 12//11//2004");
                condition = false;
            }
        } else {
            JOptionPane.showMessageDialog(ngaySinh, "Bạn không được để trống ngày sinh");
            condition = false;
        }

//email
        String EMAIL = email.getText();
        if (EMAIL.length() > 0) {
            if (!(EMAIL.contains("@"))) {
                JOptionPane.showMessageDialog(email, "Sai định dạng email, mời nhập lại!, ví dụ: test1@gmail.com ");
                condition = false;
            }
        } else {
            JOptionPane.showMessageDialog(email, "Bạn không được để trống email");
            condition = false;
        }
//sdt
        String SDt = SDT.getText();
        //4 số
        String check2 = "^\\d{10}$";
        if (SDt.length() > 0) {
            if (!SDt.matches(check2)) {
                JOptionPane.showMessageDialog(SDT, "Sai định dạng số điện thoại, nhập lại điện thoại !, ví dụ: 0123456789");
                condition = false;
            }
        } else {
            JOptionPane.showMessageDialog(SDT, "Bạn không được để trống số điện thoại bạn đọc");
            condition = false;
        }
        //tên tài khoản
        String password = register_password.getText();
        //
        String uname = register_uname.getText();
//        String mahoa = Utils.getMd5(password);
        if (uname.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(register_uname, "Bạn không được để trống tên tài khoản");
            condition = false;
        }
// tên tài khoản trùng lặp
        if (uname.equals(uname)) {
            try {
                Connection con = ConnectionDB.ketNoi();
                Statement stateMent = con.createStatement();
                String sql = "SELECT TenTaiKhoan from nhanvien WHERE TenTaiKhoan ='" + uname + "'";
                ResultSet rs = stateMent.executeQuery(sql);
                while (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Tên tài khoản đã tồn tại!");
                    condition = false;
                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

//mật khẩu
        String check = "([a-zA-Z0-9]{7,})";
        if (password.length() > 0) {

            if (!password.matches(check)) {
                JOptionPane.showMessageDialog(register_password, "Sai định dạng mật khẩu, ví dụ: yêu cầu 8 kí tự trở lên !");
                condition = false;
            }
        } else {
            JOptionPane.showMessageDialog(register_password, "Bạn không được để trống mật khẩu");
            condition = false;

        }
//retype pass
        String password2 = register_retype_password.getText();
        
        if(!password.equals(password2)){
            JOptionPane.showMessageDialog(this, "mật khẩu bạn nhập không trùng với mật khẩu trên!");
            condition = false;
        }
//Type  
                
//thong bao them thanh cong

    }

    private void ShowResult() {
        NhanVien nhanvien = list.get(list.size() - 1);
        // object 
        model.addRow(new Object[]{
            nhanvien.getMaEmployee(), nhanvien.getEmployeeName(), nhanvien.getAddress(), nhanvien.getBirthDate(), nhanvien.getEmail(), nhanvien.getPhonenumber(), nhanvien.getTenTaiKhoan(), nhanvien.getLoai()
        });
    }
    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        // TODO add your handling code here:
        setValidateForTable();
        String password = register_password.getText();
        //add vao co so du lieu
//        String IdDangKy = jComboBox_maTaiKhoan.getSelectedItem().toString();
//        int IdNhanVien = Integer.parseInt(maNhanVien.getText());
        String TenNhanVien = tenNhanVien.getText();
        String DiaChi = diaChi.getText();
        String NgaySinh = ngaySinh.getText();
        String Email = email.getText();
        String sDT = SDT.getText();
        String uname = register_uname.getText();
        String mahoa = Utils.getMd5(password);
        String Loai = "";
        if (adminRadioB.isSelected()) {
            Loai = "1";
        }
        if (nvRadioB.isSelected()) {
            Loai = "2";
        }
        condition();
        if (condition == true) {
            try {
                NhanVienDB.addData(TenNhanVien, DiaChi, NgaySinh, Email, sDT, uname, mahoa, Loai);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else if (condition == false) {
            JOptionPane.showMessageDialog(this, "Thêm tài khoản thất bại");
            condition = true;
            return;
        }
        
    ShowResult();
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table.getModel();

        //thiết lập dữ liệu cho textfield khi cột được chọn
//        String tblmadangki = model.getValueAt(Table.getSelectedRow(), 1).toString();
        String tbltennhanvien = model.getValueAt(Table.getSelectedRow(), 1).toString();
        String tbldiachi = model.getValueAt(Table.getSelectedRow(), 2).toString();
        String tblngaysinh = model.getValueAt(Table.getSelectedRow(), 3).toString();
        String tblemail = model.getValueAt(Table.getSelectedRow(), 4).toString();
        String tblsdt = model.getValueAt(Table.getSelectedRow(), 5).toString();
        String tbltentaikhoan = model.getValueAt(Table.getSelectedRow(), 6).toString();
//        String tblloai = model.getValueAt(Table.getSelectedRow(), 7).toString();
        

        // thiết lập vào textfield
//        maDangKi.setText(tblmadangki);
        tenNhanVien.setText(tbltennhanvien);
        diaChi.setText(tbldiachi);
        ngaySinh.setText(tblngaysinh);
        email.setText(tblemail);
        SDT.setText(tblsdt);
        register_uname.setText(tbltentaikhoan);
//        register_password.setText(tblloai);
    }//GEN-LAST:event_TableMouseClicked

    public void validatePassword(){
        
    }
    
    private void register_retype_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_register_retype_passwordFocusLost
        // TODO add your handling code here:
        validatePassword();
    }//GEN-LAST:event_register_retype_passwordFocusLost

    private void register_retype_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_retype_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_retype_passwordActionPerformed

    private void tenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenNhanVienActionPerformed

    private void tenNhanVienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tenNhanVienFocusLost

    }//GEN-LAST:event_tenNhanVienFocusLost

    private void adminRadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRadioBActionPerformed
        // TODO add your handling code here:
        String admin = "1";
    }//GEN-LAST:event_adminRadioBActionPerformed

    private void nvRadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvRadioBActionPerformed
        // TODO add your handling code here:
        String nv = "2";
    }//GEN-LAST:event_nvRadioBActionPerformed

    void setValidateForTable() {
        NhanVien nhanvien = new NhanVien();
        //set kieu cho doi tuong 
        //add vao table
//        String maDangNhap = jComboBox_maTaiKhoan.getSelectedItem().toString();
//        nhanvien.setMaRegister(Integer.parseInt(maDangNhap));
//        nhanvien.setMaEmployee(Integer.parseInt(maNhanVien.getText()));
        nhanvien.setEmployeeName(tenNhanVien.getText());
        nhanvien.setAddress(diaChi.getText());
        nhanvien.setEmail(email.getText());
        nhanvien.setPhonenumber(SDT.getText());
        nhanvien.setBirthDate(ngaySinh.getText());
        nhanvien.setTenTaiKhoan(register_uname.getText());
        nhanvien.setMatKhau(register_password.getText());
        nhanvien.setLoai(adminRadioB.getText());
        nhanvien.setLoai(nvRadioB.getText());
        list.add(nhanvien);
    }

    void clearField() {
//        maDangKi.setText("");
//        maNhanVien.setText("");
        tenNhanVien.setText("");
        diaChi.setText("");
        ngaySinh.setText("");
        email.setText("");
        SDT.setText("");
        register_uname.setText("");
        register_password.setText("");
        register_retype_password.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton InsertButton;
    private javax.swing.JTextField SDT;
    private javax.swing.JTable Table;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JRadioButton adminRadioB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField diaChi;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ngaySinh;
    private javax.swing.JRadioButton nvRadioB;
    private javax.swing.JPasswordField register_password;
    private javax.swing.JPasswordField register_retype_password;
    private javax.swing.JTextField register_uname;
    private javax.swing.JTextField tenNhanVien;
    // End of variables declaration//GEN-END:variables
}
