/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project2;

import static Project2.DangNhapNV.WELCOMEUSER;
import Project2.Main;
import Project2.com.dao.BanDocDB;
import Project2.entitys.BanDoc;
import Project2.entitys.MuonSach;
import Project2.entitys.QuyenSach;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author FR
 */
public class BanDocView extends javax.swing.JFrame {

    private ArrayList<BanDoc> list;
    DefaultTableModel model;

    public BanDocView() {
        initComponents();
        this.setLocationRelativeTo(null);
        list = new ArrayList<>();
        model = (DefaultTableModel) Table.getModel();
        ShowTableInfo();
    }

    //hien thi du lieu len table
    void ShowTableInfo() {
        //xoá hết tất cả các hàng trong table
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        //hiển thị tất cả các dữ liệu từ các cột lên trên table
        Vector vector = new Vector();
        try {
            Connection con = Project2.com.dao.ConnectionDB.ketNoi();
            Statement stateMent = con.createStatement();
            ResultSet rs = stateMent.executeQuery("select * from nguoidoc");
            while (rs.next()) {
                //System.out.println(rs.getInt(1)+" "+ rs.getString(2)+" "+rs.getString(3));
                vector = new Vector();
                vector.add(rs.getInt(1));
                vector.add(rs.getString(2));
                vector.add(rs.getString(3));
                vector.add(rs.getString(4));
                vector.add(rs.getString(5));
                vector.add(rs.getString(6));
                model.addRow(vector);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BanDocView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_tenBanDoc = new javax.swing.JTextField();
        txt_diaChi = new javax.swing.JTextField();
        txt_ngaySinh = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        RadioButtonHS = new javax.swing.JRadioButton();
        RadioButtonSV = new javax.swing.JRadioButton();
        InsertButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jPanel2.setBackground(new java.awt.Color(44, 63, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên Bạn Đọc:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ngày Sinh:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Địa Chỉ:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số Điện Thoại:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Loại Bạn Đọc:");

        txt_tenBanDoc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_tenBanDoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tenBanDocFocusLost(evt);
            }
        });
        txt_tenBanDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenBanDocActionPerformed(evt);
            }
        });

        txt_diaChi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_diaChi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_diaChiFocusLost(evt);
            }
        });
        txt_diaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diaChiActionPerformed(evt);
            }
        });

        txt_ngaySinh.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_ngaySinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ngaySinhFocusLost(evt);
            }
        });
        txt_ngaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ngaySinhActionPerformed(evt);
            }
        });

        txt_SDT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_SDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_SDTFocusLost(evt);
            }
        });
        txt_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SDTActionPerformed(evt);
            }
        });
        txt_SDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SDTKeyTyped(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Bạn Đọc", "Tên Bạn Đọc", "Địa Chỉ", "Ngày Sinh", "Số Điện Thoại", "Loại Bạn Đọc"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/backpage-icon.png"))); // NOI18N
        jButton1.setText("BackPage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(255, 255, 255));
        DeleteButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/delete-icon.jpg"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        buttonGroup4.add(RadioButtonHS);
        RadioButtonHS.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RadioButtonHS.setForeground(new java.awt.Color(255, 255, 255));
        RadioButtonHS.setText("Học Sinh");
        RadioButtonHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonHSActionPerformed(evt);
            }
        });

        buttonGroup4.add(RadioButtonSV);
        RadioButtonSV.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RadioButtonSV.setForeground(new java.awt.Color(255, 255, 255));
        RadioButtonSV.setText("Sinh Viên");
        RadioButtonSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSVActionPerformed(evt);
            }
        });

        InsertButton.setBackground(new java.awt.Color(255, 255, 255));
        InsertButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        InsertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/insert-icon-21.jpg"))); // NOI18N
        InsertButton.setText("Insert");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        UpdateButton.setBackground(new java.awt.Color(255, 255, 255));
        UpdateButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/update-icon.jpg"))); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        ClearButton.setBackground(new java.awt.Color(153, 153, 255));
        ClearButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/clear-icon.png"))); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("copyright © by ProjectThuVien");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_SDT))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ngaySinh))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tenBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioButtonHS, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(InsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UpdateButton)
                                        .addGap(22, 22, 22)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioButtonSV)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioButtonHS)
                            .addComponent(RadioButtonSV))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InsertButton)
                            .addComponent(DeleteButton)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thông Tin Bạn Đọc");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("-");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(374, 374, 374)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked
    //xoa du lieu tren csdl va tren table
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
            int row = Table.getSelectedRow();
//        TableModel model= Table.getModel();
            String id = (Table.getModel().getValueAt(row, 0).toString());
            BanDocDB.deleteData(Integer.parseInt(id));
        ShowTableInfo();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main main = new Main();
        
        main.welcome_user.setText(WELCOMEUSER);
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SDTActionPerformed

    private void txt_ngaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ngaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ngaySinhActionPerformed

    private void txt_diaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diaChiActionPerformed

    private void txt_tenBanDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenBanDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenBanDocActionPerformed

    private void txt_SDTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SDTKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_SDTKeyTyped
    String loaiBanDoc;
    private void RadioButtonHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonHSActionPerformed
        // TODO add your handling code here:
        loaiBanDoc = "Hoc Sinh";
    }//GEN-LAST:event_RadioButtonHSActionPerformed
    //
    void setValidateIntoTable() {
        BanDoc bandoc = new BanDoc();
        //set kieu cho doi tuong 

//         bandoc.setIdBanDoc(Integer.parseInt(maBanDoc.getText()));
        bandoc.setTenBanDocs(txt_tenBanDoc.getText());
        bandoc.setDiaChis(txt_diaChi.getText());
        bandoc.setsDT(txt_SDT.getText());
        bandoc.setNgaySinhs(txt_ngaySinh.getText());
        bandoc.setLoaiBanDoc(RadioButtonHS.getText());
        bandoc.setLoaiBanDoc(RadioButtonSV.getText());       
        //add vao bandoc 
        list.add(bandoc);
    }

    //hien thi du lieu sau khi insert
    private void ShowResult() {
        BanDoc bandoc = list.get(list.size() - 1);
        model.addRow(new Object[]{
            bandoc.getIdBanDoc(), bandoc.getTenBanDocs(), bandoc.getDiaChis(), bandoc.getNgaySinhs(), bandoc.getsDT(), bandoc.getLoaiBanDoc()
        });
    }
    boolean condition = true;

    void condition() {
//username
        String TEN = txt_tenBanDoc.getText();
        if (TEN.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(txt_tenBanDoc, "Bạn không được để trống tên bạn đọc");
            condition = false;
        }

//dia chi
        String DIACHI = txt_diaChi.getText();
        if (DIACHI.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(txt_diaChi, "Bạn không được để trống địa chỉ bạn đọc");
            condition = false;
        }

//ngay sinh
        String NGAYSINH = txt_ngaySinh.getText();
        // vi du :21//08//2004
        String check = "\\d{1,2}[//]\\d{1,2}[//]\\d{4}";
        //
        if (NGAYSINH.length() > 0) {
            if (!NGAYSINH.matches(check)) {
                JOptionPane.showMessageDialog(txt_ngaySinh, "Sai định dạng ngày sinh, nhập lại ngày tháng năm !, ví dụ: 12//11//2004");
                condition = false;
            }
        } else {
            JOptionPane.showMessageDialog(txt_ngaySinh, "Bạn không được để trống ngày sinh");
            condition = false;
        }

//sdt
        String SDt = txt_SDT.getText();
        //4 số
        String check1 = "^\\d{10}$";
        if (SDt.length() > 0) {
            if (!SDt.matches(check1)) {
                JOptionPane.showMessageDialog(txt_SDT, "Sai định dạngđiện thoại, nhập lại điện thoại !, ví dụ: 0123456789");
                condition = false;
            }
        } else {
            JOptionPane.showMessageDialog(txt_SDT, "Bạn không được để trống số điện thoại bạn đọc");
            condition = false;
        }

    }

    //them du lieu vao trong table va csdl
    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        // TODO add your handling code here:
        setValidateIntoTable();

//        int IdBanDoc = Integer.parseInt(maBanDoc.getText());
        String TenBanDoc = txt_tenBanDoc.getText();
        String DiaChi = txt_diaChi.getText();
        String NgaySinh = txt_ngaySinh.getText();
        String sDT = txt_SDT.getText();
        String LoaiBanDoc = null;
        if (RadioButtonSV.isSelected()) {
            LoaiBanDoc = RadioButtonSV.getText();
        }
        if (RadioButtonHS.isSelected()) {
            LoaiBanDoc = RadioButtonHS.getText();
        }

        condition();

        //add vao co so du lieu
        if (condition == true) {
            try {
                BanDocDB.addData(TenBanDoc, DiaChi, NgaySinh, sDT, LoaiBanDoc);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BanDocView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(BanDocView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (condition == false) {
            JOptionPane.showMessageDialog(this, "Thêm bạn đọc thất bại");
            condition = true;
            return;
        }

        ShowResult();
    }//GEN-LAST:event_InsertButtonActionPerformed
//cap nhat csdl va tren table
    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
//      int IdBanDoc = Integer.parseInt(maBanDoc.getText());
        String TenBanDoc = txt_tenBanDoc.getText();
        String DiaChi = txt_diaChi.getText();
        String NgaySinh = txt_ngaySinh.getText();
        String sDT = txt_SDT.getText();
        String LoaiBanDoc = null;
        //id duoc chon tren table
        condition();
        int row = Table.getSelectedRow();
//        TableModel model= Table.getModel();
        String IdBanDoc = (Table.getModel().getValueAt(row, 0).toString());
        //chon 1 trong 2 group button

        if (RadioButtonSV.isSelected()) {
            LoaiBanDoc = RadioButtonSV.getText();
        }
        if (RadioButtonHS.isSelected()) {
            LoaiBanDoc = RadioButtonHS.getText();
        }
        //truyen tham so vao trong ham updateData
        if (condition == true) {
            BanDocDB.updateData(Integer.parseInt(IdBanDoc), TenBanDoc, DiaChi, NgaySinh, sDT, LoaiBanDoc);
        } else if (condition == false) {
            JOptionPane.showMessageDialog(this, "Sửa tài khoản thất bại");
            condition = true;
            return;
        }
        ShowTableInfo();
    }//GEN-LAST:event_UpdateButtonActionPerformed

//xoa het tat ca cac hang tren table 
    void deleteRow() {
//            Connection con = Project2.com.dao.ConnectionDB.ketNoi();
//            Statement stateMent = con.createStatement();
//            stateMent.executeUpdate("select * from quyensach");

    }
    private void RadioButtonSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSVActionPerformed
        // TODO add your handling code here:
        loaiBanDoc = "Sinh Vien";
    }//GEN-LAST:event_RadioButtonSVActionPerformed

    void clearField() {
//         maBanDoc.setText("");
        txt_tenBanDoc.setText("");
        txt_diaChi.setText("");
        txt_ngaySinh.setText("");
        txt_SDT.setText("");
    }

    //xoa tat ca cac du lieu hien co tren jtextfield
    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void txt_tenBanDocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tenBanDocFocusLost

    }//GEN-LAST:event_txt_tenBanDocFocusLost

    private void txt_diaChiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_diaChiFocusLost

    }//GEN-LAST:event_txt_diaChiFocusLost

    private void txt_ngaySinhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ngaySinhFocusLost

    }//GEN-LAST:event_txt_ngaySinhFocusLost

    private void txt_SDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_SDTFocusLost

    }//GEN-LAST:event_txt_SDTFocusLost

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        //thiết lập dữ liệu cho các jtextfield

        DefaultTableModel model = (DefaultTableModel) Table.getModel();

        //thiết lập dữ liệu cho textfield khi cột được chọn
        String tblname = model.getValueAt(Table.getSelectedRow(), 1).toString();
        String tbldiachi = model.getValueAt(Table.getSelectedRow(), 2).toString();
        String tblngaysinh = model.getValueAt(Table.getSelectedRow(), 3).toString();
        String tblsdt = model.getValueAt(Table.getSelectedRow(), 4).toString();
        String tblloaibandoc = model.getValueAt(Table.getSelectedRow(), 5).toString();

        // thiết lập vào textfield
        txt_tenBanDoc.setText(tblname);
        txt_diaChi.setText(tbldiachi);
        txt_ngaySinh.setText(tblngaysinh);
        txt_SDT.setText(tblsdt);
        if (RadioButtonSV.isSelected()) {
            tblloaibandoc = RadioButtonSV.getText();
        }
        if (RadioButtonHS.isSelected()) {
            tblloaibandoc = RadioButtonHS.getText();
        }
    }//GEN-LAST:event_TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanDocView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanDocView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanDocView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanDocView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanDocView().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton InsertButton;
    private javax.swing.JRadioButton RadioButtonHS;
    private javax.swing.JRadioButton RadioButtonSV;
    public javax.swing.JTable Table;
    private javax.swing.JButton UpdateButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_ngaySinh;
    private javax.swing.JTextField txt_tenBanDoc;
    // End of variables declaration//GEN-END:variables
}
