/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project2;

import Project2.entitys.MuonSach;
import Project2.BanDocInfo;
import static Project2.DangNhapNV.MaNhanVien1;
import static Project2.DangNhapNV.WELCOMEUSER;
import Project2.Main;
import Project2.SachInfo;
import Project2.com.dao.MuonSachDB;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author FR
 */
public class MuonSachView extends javax.swing.JFrame {

    private ArrayList<MuonSachView> list;
    DefaultTableModel model;
    DefaultTableModel modelNhanVien;
    DefaultTableModel modelQuyenSach;
    DefaultTableModel modelNguoiDoc;

    public MuonSachView() {
        initComponents();
        this.setLocationRelativeTo(null);
//        MuonSachView jtRowData2 = new MuonSachView();
        String id_NhanVien;
        list = new ArrayList<>();
        model = (DefaultTableModel) TableMuonSach.getModel();
//        modelNhanVien = (DefaultTableModel) TableNhanVien.getModel();
        modelQuyenSach = (DefaultTableModel) TableQuyenSach.getModel();
        modelNguoiDoc = (DefaultTableModel) TableNguoiDoc.getModel();
        ShowMuonSachInfo();
        ShowNguoiDocInfo();
//        ShowNhanVienInfo();
        ShowQuyenSachInfo();
//            Management.muonSach_ = this;
//        ComboBoxIdEmployee();
//        ComboBoxIdReader();
//        ComboBoxIdBook();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        InsertButton2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        giaThue = new javax.swing.JTextField();
        ngayTra = new javax.swing.JTextField();
        ngayMuon = new javax.swing.JTextField();
        BackPage = new javax.swing.JButton();
        InsertButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMuonSach = new javax.swing.JTable();
        InfoLoaiSach = new javax.swing.JButton();
        InfoNguoiDoc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableNguoiDoc = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableQuyenSach = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        id_Sach = new javax.swing.JTextField();
        id_NguoiDoc = new javax.swing.JTextField();
        id_NhanVien = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        InsertButton2.setBackground(new java.awt.Color(255, 255, 255));
        InsertButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        InsertButton2.setText("Insert");
        InsertButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton2ActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("copyright © by ProjectThuVien");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Mượn Sách");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 65)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("x");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(555, 555, 555)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(44, 63, 80));
        jPanel4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel4FocusGained(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Người Đọc:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Sách:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ngày Mượn:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ngày Trả:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Giá Thuê:");

        giaThue.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        giaThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaThueActionPerformed(evt);
            }
        });

        ngayTra.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ngayTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngayTraActionPerformed(evt);
            }
        });

        ngayMuon.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ngayMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngayMuonActionPerformed(evt);
            }
        });

        BackPage.setBackground(new java.awt.Color(255, 255, 51));
        BackPage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BackPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/backpage-icon.png"))); // NOI18N
        BackPage.setText("BackPage");
        BackPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackPageActionPerformed(evt);
            }
        });

        InsertButton.setBackground(new java.awt.Color(255, 255, 255));
        InsertButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        InsertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/insert-icon-21.jpg"))); // NOI18N
        InsertButton.setText(" Insert");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        UpdateButton.setBackground(new java.awt.Color(255, 255, 255));
        UpdateButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/update-icon.jpg"))); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(255, 255, 255));
        DeleteButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/delete-icon.jpg"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        TableMuonSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID Nhân Viên", "ID Người Đọc", "ID Sách", "Gía Thuê", "Ngày Mượn", "Ngày Trả", "Trạng Thái"
            }
        ));
        TableMuonSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMuonSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMuonSach);

        InfoLoaiSach.setBackground(new java.awt.Color(255, 255, 255));
        InfoLoaiSach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        InfoLoaiSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/bookInfo-icon.jpg"))); // NOI18N
        InfoLoaiSach.setText("InfoBook");
        InfoLoaiSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoLoaiSachActionPerformed(evt);
            }
        });

        InfoNguoiDoc.setBackground(new java.awt.Color(255, 255, 255));
        InfoNguoiDoc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        InfoNguoiDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/readerInfo-icon.png"))); // NOI18N
        InfoNguoiDoc.setText("InfoReader");
        InfoNguoiDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoNguoiDocActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/clear-icon.png"))); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Nhân Viên:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Trạng Thái Sách:");

        buttonGroup1.add(yes);
        yes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        yes.setForeground(new java.awt.Color(255, 255, 255));
        yes.setText("Đã Trả Sách");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        buttonGroup1.add(no);
        no.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        no.setForeground(new java.awt.Color(255, 255, 255));
        no.setText("Chưa Trả Sách");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        TableNguoiDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Người Đọc", "Tên Người Đọc", "Địa Chỉ", "Ngày Sinh"
            }
        ));
        TableNguoiDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNguoiDocMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableNguoiDoc);

        TableQuyenSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Thể Loại", "NXB"
            }
        ));
        TableQuyenSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableQuyenSachMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableQuyenSach);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Người Đọc");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Quyển Sách");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Bảng Mượn Sách");

        id_Sach.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        id_NguoiDoc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        id_NhanVien.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        id_NhanVien.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("copyright © by ProjectThuVien");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(id_Sach, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(50, 50, 50)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ngayTra, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ngayMuon, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(giaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(yes)
                                    .addGap(18, 18, 18)
                                    .addComponent(no)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(id_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(id_NguoiDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane3)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 11, Short.MAX_VALUE))))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(InsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(InfoLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(InfoNguoiDoc)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(BackPage)
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(1346, 1346, 1346))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_NguoiDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_Sach, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InfoLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InfoNguoiDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BackPage, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InsertButton)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void giaThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaThueActionPerformed

    private void ngayTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngayTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayTraActionPerformed

    private void ngayMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngayMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayMuonActionPerformed

    private void BackPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackPageActionPerformed
        Main main = new Main();
        main.welcome_user.setText(WELCOMEUSER);
        main.setVisible(true);
        this.setVisible(false);

//        borrowBook brb = new borrowBook();
//        brb.setVisible(true);
//        this.setVisible(false);

    }//GEN-LAST:event_BackPageActionPerformed

    public void ShowQuyenSachInfo() {
        Vector vector = new Vector();
        try {
            Connection con = Project2.com.dao.ConnectionDB.ketNoi();
            Statement stateMent = con.createStatement();
            ResultSet rs = stateMent.executeQuery("select * from quyensach");
            while (rs.next()) {
                //System.out.println(rs.getInt(1)+" "+ rs.getString(2)+" "+rs.getString(3));
                vector = new Vector();
                vector.add(rs.getInt(1));
                vector.add(rs.getString(2));
                vector.add(rs.getString(3));
                vector.add(rs.getString(4));
                modelQuyenSach.addRow(vector);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(QuyenSachView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void ShowNguoiDocInfo() {
        Vector vector = new Vector();
        try {
            Connection con = Project2.com.dao.ConnectionDB.ketNoi();
            Statement stateMent = con.createStatement();
            ResultSet rs = stateMent.executeQuery("select * from nguoidoc");
            while (rs.next()) {
                //System.out.println(rs.getInt(1)+" "+ rs.getString(2)+" "+rs.getString(3));
                vector = new Vector();
                vector.add(rs.getInt(1));
                vector.add(rs.getString(2));
                vector.add(rs.getString(3));
                vector.add(rs.getString(4));
                modelNguoiDoc.addRow(vector);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MuonSachView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
//
    void ShowMuonSachInfo() {
        //xoá hết tất cả các hàng trong table
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        //hiển thị tất cả các dữ liệu từ các cột lên trên table
        Vector vector = new Vector();
        try {
            Connection con = Project2.com.dao.ConnectionDB.ketNoi();
            Statement stateMent = con.createStatement();
            ResultSet rs = stateMent.executeQuery("select * from muonsach");
            while (rs.next()) {
                //System.out.println(rs.getInt(1)+" "+ rs.getString(2)+" "+rs.getString(3));
                vector = new Vector();
                vector.add(rs.getInt(1));
                vector.add(rs.getString(2));
                vector.add(rs.getString(3));
                vector.add(rs.getString(4));
                vector.add(rs.getString(5));
                vector.add(rs.getString(6));
                vector.add(rs.getString(7));
                vector.add(rs.getString(8));
                model.addRow(vector);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MuonSachView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    Boolean condition = true;

    void condition() {
        //id nhan vien
        String NHANVIEN = id_NhanVien.getText();

        if (NHANVIEN.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(id_NhanVien, "Bạn không được để trống mã nhân viên");
            condition = false;
        }
        //id nguoi doc
        String NGUOIDOC = id_NguoiDoc.getText();

        if (NGUOIDOC.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(id_NguoiDoc, "Bạn không được để trống giá thuê");
            condition = false;
        }
        //id sach
        String QUYENSACH = id_Sach.getText();

        if (QUYENSACH.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(id_Sach, "Bạn không được để trống giá thuê");
            condition = false;
        }
        //ngay muon
        String NGAYMUON = ngayMuon.getText();
        String check = "\\d{1,2}[//]\\d{1,2}[//]\\d{4}";
        if (NGAYMUON.length() > 0) {
            if (!NGAYMUON.matches(check)) {
                JOptionPane.showMessageDialog(ngayMuon, "Sai định dạng ngày , nhập lại ngày tháng năm !, ví dụ: 12//11//2004");
                condition = false;
            }
        } else {
            JOptionPane.showMessageDialog(ngayMuon, "Bạn không được để trống ngày sinh");
            condition = false;
        }

        //ngay tra
        String NGAYTRA = ngayTra.getText();
        String check2 = "\\d{1,2}[//]\\d{1,2}[//]\\d{4}";
        if (NGAYTRA.length() > 0) {
            if (!NGAYTRA.matches(check2)) {
                JOptionPane.showMessageDialog(ngayTra, "Sai định dạng ngày , nhập lại ngày tháng năm !, ví dụ: 12//11//2004");
                condition = false;
            }
        } else {
            JOptionPane.showMessageDialog(ngayTra, "Bạn không được để trống ngày sinh");
            condition = false;
        }

        //gia tien
        String GIATIEN = giaThue.getText();

        if (GIATIEN.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(giaThue, "Bạn không được để trống giá thuê");
            condition = false;
        }
    }
//    public static String MaNhanVien ;
    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        // TODO add your handling code here:
        //khoi tao doi tuong
//        addIntoTable();
        //add vao co so du lieu
//        String MaNhanVien = jComboBox_IdNhanVien.getSelectedItem().toString();
//        String MaNguoiDoc = jComboBox_IdNguoiDoc.getSelectedItem().toString();
//        String MaSach = jComboBox_IdSach.getSelectedItem().toString();
        String MaNhanVien = MaNhanVien1;
        String MaNguoiDoc = id_NguoiDoc.getText();
        String MaSach = id_Sach.getText();
        float GiaThue = Float.parseFloat(giaThue.getText());
        String NgayMuonSach = ngayMuon.getText();
        String NgayTraSach = ngayTra.getText();
        String TrangThai = null;
        if (yes.isSelected()) {
            TrangThai = yes.getText();
        }
        if (no.isSelected()) {
            TrangThai = no.getText();
        }
        //truyen tham so vao trong ham addData o file Project.com.dao phan MuonSachDB
        condition();
        if (condition == true) {
            try {
                MuonSachDB.addData(MaNhanVien, MaNguoiDoc, MaSach, GiaThue, NgayMuonSach, NgayTraSach, TrangThai);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MuonSachView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MuonSachView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (condition == false) {
            JOptionPane.showMessageDialog(this, "Thêm tài khoản thất bại");
            condition = true;
            return;
        }

        ShowMuonSachInfo();
//        ShowResult();

    }//GEN-LAST:event_InsertButtonActionPerformed

//    private void ShowResult() {
//        MuonSachView muonsach = list.get(list.size() - 1);
//        model.addRow(new Object[]{
//            muonsach.getIdForm(), muonsach.getIdNguoiDoc(), muonsach.getIdSach(), muonsach.getNgayMuon(), muonsach.getNgayTra(), muonsach.getGiaTien()
//        });
//    }

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
//        int MaForm = Integer.parseInt(maForm.getText());
        String MaNhanVien = id_NhanVien.getText();
        String MaNguoiDoc = id_NguoiDoc.getText();
        String MaSach = id_Sach.getText();
        String NgayMuonSach = ngayMuon.getText();
        String NgayTraSach = ngayTra.getText();
        int row = TableMuonSach.getSelectedRow();
//        TableModel model= Table.getModel();
        String IdNhanVien = (TableMuonSach.getModel().getValueAt(row, 0).toString());
        float GiaThue = Float.parseFloat(giaThue.getText());
        //lua chon radio button
        String TrangThai = null;
        if (yes.isSelected()) {
            TrangThai = yes.getText();
        }
        if (no.isSelected()) {
            TrangThai = no.getText();
        }
        //truyen tham so sang ham updateData
        condition();
        if (condition == true) {
            MuonSachDB.updateData(Integer.parseInt(IdNhanVien), MaNhanVien, MaNguoiDoc, MaSach, GiaThue, NgayMuonSach, NgayTraSach, TrangThai);
        } else if (condition == false) {
            JOptionPane.showMessageDialog(this, "Sửa tài khoản thất bại");
            condition = true;
            return;
        }
        ShowMuonSachInfo();
    }//GEN-LAST:event_UpdateButtonActionPerformed


    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        int row = TableMuonSach.getSelectedRow();
        String Ma = (TableMuonSach.getModel().getValueAt(row, 0).toString());
            MuonSachDB.deleteData(Integer.parseInt(Ma));
//        int MaForm = Integer.parseInt(maForm.getText());
//        (new QuyenSachView()).deleteData(Integer.parseInt(Ma));
        ShowMuonSachInfo();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void InfoLoaiSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoLoaiSachActionPerformed
        // TODO add your handling code here:
        SachInfo si = new SachInfo();
        si.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InfoLoaiSachActionPerformed

    private void InsertButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertButton2ActionPerformed

    private void InfoNguoiDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoNguoiDocActionPerformed
        // TODO add your handling code here:
        BanDocInfo bdi = new BanDocInfo();
        bdi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InfoNguoiDocActionPerformed

    private void jPanel4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4FocusGained
    void clearField() {
        id_NhanVien.setText("");
        id_NguoiDoc.setText("");
        id_Sach.setText("");
        ngayMuon.setText("");
        ngayTra.setText("");
        giaThue.setText("");
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TableMuonSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMuonSachMouseClicked
        // TODO add your handling code here:
        //lấy thông tin từ bảng Mượn Sách
        DefaultTableModel model = (DefaultTableModel) TableMuonSach.getModel();

        //thiết lập dữ liệu cho textfield khi cột được chọn
//        String tblId_NhanVien = model.getValueAt(TableMuonSach.getSelectedRow(), 1).toString();
        String tblId_NguoiDoc = model.getValueAt(TableMuonSach.getSelectedRow(), 2).toString();
        String tblId_QuyenSach = model.getValueAt(TableMuonSach.getSelectedRow(), 3).toString();
        String tblgiathue = model.getValueAt(TableMuonSach.getSelectedRow(), 4).toString();
        String tblngaymuon = model.getValueAt(TableMuonSach.getSelectedRow(), 5).toString();
        String tblngaytra = model.getValueAt(TableMuonSach.getSelectedRow(), 6).toString();

        // thiết lập vào textfield
//        id_NhanVien.setText(tblId_NhanVien);
        id_NguoiDoc.setText(tblId_NguoiDoc);
        id_Sach.setText(tblId_QuyenSach);
        ngayMuon.setText(tblngaymuon);
        ngayTra.setText(tblngaytra);
        giaThue.setText(tblgiathue);
    }//GEN-LAST:event_TableMuonSachMouseClicked
    String trangThai;
    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
        
        trangThai = "Đã Trả Sách";
    }//GEN-LAST:event_yesActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
        trangThai = "Chưa Trả Sách";
    }//GEN-LAST:event_noActionPerformed

    private void TableNguoiDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNguoiDocMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TableNguoiDoc.getModel();

        //thiết lập dữ liệu cho textfield khi cột được chọn
        String tblId_NguoiDoc = model.getValueAt(TableNguoiDoc.getSelectedRow(), 0).toString();

        // thiết lập vào textfield
          id_NguoiDoc.setText(tblId_NguoiDoc);
    }//GEN-LAST:event_TableNguoiDocMouseClicked

    private void TableQuyenSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableQuyenSachMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TableQuyenSach.getModel();

        //thiết lập dữ liệu cho textfield khi cột được chọn
        String tblId_Sach = model.getValueAt(TableQuyenSach.getSelectedRow(), 0).toString();

        // thiết lập vào textfield
        id_Sach.setText(tblId_Sach);
    }//GEN-LAST:event_TableQuyenSachMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuonSachView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuonSachView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuonSachView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuonSachView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuonSachView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackPage;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton InfoLoaiSach;
    private javax.swing.JButton InfoNguoiDoc;
    private javax.swing.JButton InsertButton;
    private javax.swing.JButton InsertButton2;
    private javax.swing.JTable TableMuonSach;
    private javax.swing.JTable TableNguoiDoc;
    private javax.swing.JTable TableQuyenSach;
    private javax.swing.JButton UpdateButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField giaThue;
    private javax.swing.JTextField id_NguoiDoc;
    public javax.swing.JLabel id_NhanVien;
    private javax.swing.JTextField id_Sach;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField ngayMuon;
    private javax.swing.JTextField ngayTra;
    private javax.swing.JRadioButton no;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
}
