/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project2;

import static Project2.DangNhapNV.WELCOMEUSER;
import Project2.Main;
import Project2.com.dao.QuyenSachDB;
import Project2.entitys.QuyenSach;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Minh PC
 */
public class QuyenSachView extends javax.swing.JFrame {
    
    private ArrayList<QuyenSach> list;
    DefaultTableModel model;

    /**
     * Creates new form NguoiMuaSach
     */
    public QuyenSachView() {
        initComponents();
        this.setLocationRelativeTo(null);
        list = new ArrayList<>();
        model = (DefaultTableModel) Table.getModel();
        ShowTableInfo();
        jTextArea1.setEditable(false);
    }

    void ShowTableInfo() {
        //xoá hết tất cả các hàng trong table
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        //hiển thị tất cả các dữ liệu từ các cột lên trên table
        Vector vector = new Vector();
        try {
            Connection con = Project2.com.dao.ConnectionDB.ketNoi();
            Statement stateMent = con.createStatement();
            ResultSet rs = stateMent.executeQuery("select * from quyensach");
            while (rs.next()) {
                //System.out.println(rs.getInt(1)+" "+ rs.getString(2)+" "+rs.getString(3));
                vector = new Vector();
                vector.add(rs.getInt(1));
                vector.add(rs.getString(2));
                vector.add(rs.getString(3));
                vector.add(rs.getString(4));
                vector.add(rs.getString(5));
                vector.add(rs.getString(6));
                model.addRow(vector);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(QuyenSachView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        txt_theLoai = new javax.swing.JTextField();
        txt_nxb = new javax.swing.JTextField();
        txt_giaTien = new javax.swing.JTextField();
        InsertButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        txt_tenSach = new javax.swing.JTextField();
        BackPage = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ChooseIMGButton = new javax.swing.JButton();
        lbl_image = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelClose = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jPanel2.setBackground(new java.awt.Color(44, 63, 80));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Thể Loại", "Ngày XB", "Giá Tiền", "anh"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(5).setResizable(false);
        }

        txt_theLoai.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_theLoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_theLoaiFocusLost(evt);
            }
        });
        txt_theLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_theLoaiActionPerformed(evt);
            }
        });

        txt_nxb.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_nxb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nxbFocusLost(evt);
            }
        });

        txt_giaTien.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        InsertButton.setBackground(new java.awt.Color(255, 255, 255));
        InsertButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        InsertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/insert-icon-21.jpg"))); // NOI18N
        InsertButton.setText("Insert");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   Thể Loại");

        UpdateButton.setBackground(new java.awt.Color(255, 255, 255));
        UpdateButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/update-icon.jpg"))); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("       NXB");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("   Tên Sách");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("    Giá Tiền");

        DeleteButton.setBackground(new java.awt.Color(255, 255, 255));
        DeleteButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/delete-icon.jpg"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        ClearButton.setBackground(new java.awt.Color(153, 153, 255));
        ClearButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/clear-icon.png"))); // NOI18N
        ClearButton.setText("clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        txt_tenSach.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_tenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenSachActionPerformed(evt);
            }
        });

        BackPage.setBackground(new java.awt.Color(255, 255, 51));
        BackPage.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BackPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project2/picture/backpage-icon.png"))); // NOI18N
        BackPage.setText("BackPage");
        BackPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackPageActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("copyright © by ProjectThuVien");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("  Hình Ảnh:");

        ChooseIMGButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ChooseIMGButton.setText("Chọn Một Ảnh");
        ChooseIMGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseIMGButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(txt_theLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(16, 16, 16)
                                .addComponent(txt_tenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(txt_giaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(txt_nxb, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(ChooseIMGButton, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(InsertButton)
                        .addGap(51, 51, 51)
                        .addComponent(UpdateButton)
                        .addGap(57, 57, 57)
                        .addComponent(DeleteButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(BackPage)
                                .addGap(114, 114, 114))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_theLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nxb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_giaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChooseIMGButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackPage)
                        .addGap(42, 42, 42)
                        .addComponent(ClearButton)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111))))
        );

        jLabelClose.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("-");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("          THÔNG TIN QUẢN LÝ SÁCH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelClose)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_theLoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_theLoaiFocusLost
        // TODO add your handling code here:
//        String LOAISACH = txt_theLoai.getText();
//        //
//        if (LOAISACH.length() > 0) {
//
//        } else {
//            JOptionPane.showMessageDialog(txt_theLoai, "Bạn không được để trống thể loại ");
//        }
    }//GEN-LAST:event_txt_theLoaiFocusLost

    private void txt_theLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_theLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_theLoaiActionPerformed

    private void txt_nxbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nxbFocusLost
        // TODO add your handling code here:
//        String NGAYXUATBAN = txt_nxb.getText();
//        // vi du :21//08//2004
//        String check = "\\d{1,2}[//]\\d{1,2}[//]\\d{4}";
//        //
//        if (NGAYXUATBAN.length() > 0) {
//            if (!NGAYXUATBAN.matches(check)) {
//                JOptionPane.showMessageDialog(txt_nxb, "Sai định dạng ngày xuất bản, nhập lại ngày tháng năm !, ví dụ: 12/11/2004");
//            }
//        } else {
//            JOptionPane.showMessageDialog(txt_nxb, "Bạn không được để trống ngày xuất bản");
//        }
    }//GEN-LAST:event_txt_nxbFocusLost
    boolean condition = true;

    void condition() {
//ten        
        String TEN = txt_tenSach.getText();
        //
        if (TEN.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(txt_tenSach, "Bạn không được để trống tên sách");
            condition = false;
        }

//the loai
        String LOAISACH = txt_theLoai.getText();
        //
        if (LOAISACH.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(txt_theLoai, "Bạn không được để trống thể loại ");
            condition = false;
        }
//NXB
        String NGAYXUATBAN = txt_nxb.getText();
        // vi du :21//08//2004
        String check = "\\d{1,2}[//]\\d{1,2}[//]\\d{4}";
        //
        if (NGAYXUATBAN.length() > 0) {
            if (!NGAYXUATBAN.matches(check)) {

                JOptionPane.showMessageDialog(txt_nxb, "Sai định dạng ngày xuất bản, nhập lại ngày tháng năm !, ví dụ: 12/11/2004");
                condition = false;
            }
        } else {
            JOptionPane.showMessageDialog(txt_nxb, "Bạn không được để trống ngày xuất bản");
            condition = false;
        }

//Gia Tien
        String GIATIEN = txt_giaTien.getText();

        if (GIATIEN.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(txt_giaTien, "Bạn không được để trống giá thuê");
            condition = false;
        }
    }

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        // TODO add your handling code here:
        //khoi tao doi tuong
//        setIntoTable();
        //add vao co so du lieu
//        int ma = Integer.parseInt(maSach.getText());
        String ten = txt_tenSach.getText();
        String theloai = txt_theLoai.getText();
        String nXB = txt_nxb.getText();
        float giatien = Float.parseFloat(txt_giaTien.getText());
        String IMG = jTextArea1.getText();
        System.out.println(lbl_image);
        condition();
        if (condition == true) {
            try {
                QuyenSachDB.addData(ten, theloai, nXB, giatien,IMG);
                ShowTableInfo();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(QuyenSachView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(QuyenSachView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (condition == false) {
            JOptionPane.showMessageDialog(this, "Thêm sách thất bại");
            condition = true;
            return;
        }
//        ShowResult();
        //hien thi phan add vao table(1)

    }//GEN-LAST:event_InsertButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
//        int ma = Integer.parseInt(maSach.getText());
        String ten = txt_tenSach.getText();
        String theloai = txt_theLoai.getText();
        String nXB = txt_nxb.getText();
        float giatien = Float.parseFloat(txt_giaTien.getText());
        int row = Table.getSelectedRow();
//        TableModel model= Table.getModel();
        String IMG =  jTextArea1.getText();
        System.out.println(IMG); //debug
        String ma = (Table.getModel().getValueAt(row, 0).toString());
        if (condition == true) {
            QuyenSachDB.updateData(Integer.parseInt(ma), ten, theloai, nXB, giatien,IMG);
            condition();
            ShowTableInfo();
        } else if (condition == false) {
            JOptionPane.showMessageDialog(this, "Sửa tài khoản thất bại");
            condition = true;
            return;
        }
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        int row = Table.getSelectedRow();
//        TableModel model= Table.getModel();
        String maSach = (Table.getModel().getValueAt(row, 0).toString());
        condition();
            QuyenSachDB.deleteData(Integer.parseInt(maSach));
     
        ShowTableInfo();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        clearField();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void txt_tenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenSachActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void BackPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackPageActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.welcome_user.setText(WELCOMEUSER);
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackPageActionPerformed
    String filename;
    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table.getModel();

        //thiết lập dữ liệu cho textfield khi cột được chọn
        String tblbookname = model.getValueAt(Table.getSelectedRow(), 1).toString();
        String tbltype = model.getValueAt(Table.getSelectedRow(), 2).toString();
        String tblnxuatban = model.getValueAt(Table.getSelectedRow(), 3).toString();
        String tblgiatien = model.getValueAt(Table.getSelectedRow(), 4).toString();
            filename = model.getValueAt(Table.getSelectedRow(), 5).toString();
            System.out.println(filename);
        // thiết lập vào textfield
        txt_tenSach.setText(tblbookname);
        txt_theLoai.setText(tbltype);
        txt_nxb.setText(tblnxuatban);
        txt_giaTien.setText(tblgiatien);
        jTextArea1.setText(filename);
        ImageIcon imgicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH));
        lbl_image.setIcon(imgicon);
    }//GEN-LAST:event_TableMouseClicked

    private void ChooseIMGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseIMGButtonActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);
       if (result == JFileChooser.APPROVE_OPTION) {
    File f = chooser.getSelectedFile();
        System.out.println(f.getAbsolutePath());
        filename = f.getAbsolutePath();
        System.out.println(filename);
        ImageIcon imgicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH));
        lbl_image.setIcon(imgicon);
        try{
        jTextArea1.setText(String.valueOf(chooser.getSelectedFile()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            } else if (result == JFileChooser.CANCEL_OPTION) {
    System.out.println("Cancel was selected");
        } 
    }//GEN-LAST:event_ChooseIMGButtonActionPerformed
    //Add co so du lieu   

    void setIntoTable() {
        QuyenSach quyensach = new QuyenSach();
        //set kieu cho doi tuong 
        //add vao table
//        quyensach.setId(Integer.parseInt(maSach.getText()));
        quyensach.setName(txt_tenSach.getText());
        quyensach.setMoney(Float.parseFloat(txt_giaTien.getText()));
        quyensach.setKieu(txt_theLoai.getText());   
        quyensach.setDob(txt_nxb.getText());
        list.add(quyensach);
    }

    private void ShowResult() {
        //add vao table(1)
        QuyenSach quyensach = list.get(list.size() - 1);
        model.addRow(new Object[]{
            quyensach.getId(), quyensach.getName(), quyensach.getKieu(), quyensach.getDob(), quyensach.getMoney()
        });
    }

//    public void showData() {
////        try {
////            Connection con = (new CollectionJava()).ketNoi();
////            Statement stateMent = con.createStatement();
////            ResultSet rs = stateMent.executeQuery("select * from loaisach");
////            while(rs.next()){
////                System.out.println(rs.getInt(1)+" "+ rs.getString(2)+" "+rs.getString(3));
////            }
////        } catch (ClassNotFoundException | SQLException ex) {
////            Logger.getLogger(LoaiSach.class.getName()).log(Level.SEVERE, null, ex);
////        }
//    }
    void clearField() {
//        maSach.setText("");
        txt_tenSach.setText("");
        txt_theLoai.setText("");
        txt_nxb.setText("");
        txt_giaTien.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuyenSachView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuyenSachView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuyenSachView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuyenSachView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuyenSachView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackPage;
    private javax.swing.JButton ChooseIMGButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton InsertButton;
    private javax.swing.JTable Table;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JTextField txt_giaTien;
    private javax.swing.JTextField txt_nxb;
    private javax.swing.JTextField txt_tenSach;
    private javax.swing.JTextField txt_theLoai;
    // End of variables declaration//GEN-END:variables
}
